### ISSUE TITLE
Add in using dictionaries?

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-text-analysis#13]
Could use some opinions on this,  I was thinking maybe we should add a section on using dictionaries.  They are such a useful data structure.  My concern is that maybe we don't need them for the end using nltk so maybe it isn't worth teaching?

Thoughts from others?

**Comment by steve-meyer** [comment]
Yes! I personally would even consider going as far as defaultdict.

`>>> word_counts = defaultdict(int)
>>> for word in "to be or not to be".split(" "):
...   word_counts[word] += 1
... 
>>> word_counts
defaultdict(<class 'int'>, {'to': 2, 'be': 2, 'or': 1, 'not': 1})
`

**Comment by sstevens2** [comment]
This is something I could use to learn about too. I've never used a defaultdict before!

**Comment by Karl-Holten** [comment]
This may be confusing, given that Gensim has its own dictionary object that is distinct from python dictionaries. Maybe this is a distinction that students could handle but we would want to make sure to make the two distinct.
https://radimrehurek.com/gensim/corpora/dictionary.html
