### ISSUE TITLE
Do we need anything dealing with integers and floats?

### ISSUE THREAD

**Issue by caseyschacher** [carpentries-incubator/python-text-analysis#24]
There are several episodes that contain exercises/information about using numbers and floats. Given that we need to trim the fat as much as possible, is it reasonable to remove all of those bits?

Examples:

- Episode 3 has a bunch on working with numbers.  It might be useful to teach how to convert a number to string type maybe?

- Episode 4 uses mathematics as examples.  Perhaps all examples should use string data type instead?

- Episode 6 introduces the Math library but probably shouldn't.  We should introduce NLTK instead.  This entire episode needs to be rewritten.

- Episode 11:  the "pressures" and "primes" examples should be converted to something string-based.

- Episode 12:  many examples use numbers.  slight alteration to make them string based would be good.

- Episode 13 is almost entirely integer based.  Also, it introduces Pandas (is this what we need to do at this point?)

**Comment by sstevens2** [comment]
Thanks for finding all those specific locations @caseyschacher!  I think we should swtich to using text as much as possible.  An easy swap out for some of the simple stuff might be names.  Like for addition we could show something like 

```
firstname="Sarah"
lastname="Stevens"
print(firstname+" "+lastname)
```

**Comment by caseyschacher** [comment]
Also containing interger-based examples:

- Epidsode 1:  "more math," "Change an Existing Cell from Code to Markdown",  sections

- Epidsode 2:  age calulations
