### ISSUE TITLE
What are the example themes that we will be using throughout?

### ISSUE THREAD

**Issue by caseyschacher** [carpentries-incubator/python-text-analysis#35]
As I'm creating code examples for the various functions in my episode, it occurred to me that we may want to align the themes of the examples we are using throughout (either in process or at the end as we are doing the final edit).

I like to use silly examples (i.e. favoritePets = ['cat', 'dog', 'bird']) when I teach, but my impression is that Carpentries tend to use more serious examples.  In fact, everyone might end up using different themes as they write their episodes, and it could end up a bit of a crazy quilt.

Should I just proceed with my silly examples, and we can modify them later to bring them into alignment with the rest of the episodes?

**Comment by sstevens2** [comment]
In the sprint today we talked about using Shakespeare examples.  What do other folks think?  @maxgray20 @maijxyooj @Karl-Holten @claremichaud @annhanlon
