### ISSUE TITLE
Consistent quotes

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-text-analysis#38]
I suggest we use " " for strings consistently throughout the lesson.

Any objections? @Karl-Holten @caseyschacher @claremichaud @annhanlon @maijxyooj @maxgray20 

Also we should maybe purposely run into a situation where you would need raw quotes.

**Comment by maxgray20** [comment]
No objections from me! Cheers, Max

Maxwell Gray
MLIS Student, iSchool
PhD Student, Department of English
University of Wisconsin-Madison
https://www.maxgray20.com
