### ISSUE TITLE
Reorder lesson

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-text-analysis#7]
Maybe move up Lists/loops/conditionals earlier and move libraries later.

**Comment by annhanlon** [comment]
Move set up programming environment to morning (1st part of what is currently the day one afternoon session); 
Launch the JupyterLab server.
Create a Jupyter notebook.
Create a new Python script.
Understand the difference between a Python script and a Jupyter notebook.
Create and run Python cells in a notebook.
Shutdown the JupyterLab server.

**Comment by tobyhodges** [comment]
Dropping in here to say: if you think you're likely to want to rearrange the order of episodes quite often while you're designing the lesson, you might want to use the optional `episode_order` field in your `_config.yml`. If you include this field, which takes an array of episode slugs (the filenames without the `.md` extension), your episodes will be ordered as you specify in the array. E.g.

```
episode_order:
    introduction
    first_steps
    middle_episode
    finishing_up
    conclusions
```

It's much easier to adjust the order of episodes this way, compared to re-naming/re-numbering the episode files whenever you need to reorganise the material.

With `extras_order`, you can do the same thing with Extras.

**Comment by sstevens2** [comment]
Thanks for the tip @tobyhodges!  We might have to give that a try.
